services:
  grpc-python-server-tester:
    build:
      context: .
      dockerfile: ./services/grpc-python-server/Dockerfile
      target: tester

  grpc-python-server:
    build:
      context: .
      dockerfile: ./services/grpc-python-server/Dockerfile
    ports:
      - 50051:50051
    networks:
      - grpc-network

  grpc-python-client:
    build:
      context: .
      dockerfile: ./services/grpc-python-client/Dockerfile
    networks:
      - grpc-network

  grpc-nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - grpc-network

networks:
  grpc-network: