services:
  grpc-python-server-tester:
    build:
      context: .
      dockerfile: ./services/grpc-python-server/Dockerfile
      target: tester

  grpc-python-server:
    build:
      context: .
      dockerfile: ./services/grpc-python-server/Dockerfile
    ports:
      - 50051:50051
    networks:
      - grpc-network

  grpc-python-client:
    build:
      context: .
      dockerfile: ./services/grpc-python-client/Dockerfile
    environment:
      - NGINX_GRPC_GATEWAY_FQDN=grpc-nginx
      - NGINX_GRPC_GATEWAY_PORT=1443
    volumes:
      - ./services/nginx/cert.pem:/cacerts/cert.pem:ro
    networks:
      - grpc-network

  grpc-nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./services/nginx/key.pem:/etc/nginx/ssl/key.pem:ro
      - ./services/nginx/cert.pem:/etc/nginx/ssl/cert.pem:ro
    ports:
      - 1443:1443
    networks:
      - grpc-network

networks:
  grpc-network: